version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./:/usr/share/nginx/html/terminal
    restart: always
    # 如果有其他服务，可以添加networks配置
    networks:
      - web-network

networks:
  web-network:
    driver: bridge